format = """
[ ](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#FCA17D)\
[](fg:#FCA17D)\
$fill\
[](#33658A)\
$time\
[ ](#33658A)\
$line_break\
[ $character](fg:#FFFFFF)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false
[fill]
symbol = " "

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#9A348E bold fg:#FFFFFF"
style_root = "bg:#9A348E bold fg:#FFFFFF"
format = '[ $user ]($style)'

[directory]
style = "bg:#DA627D fg:#FFFFFF"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#FCA17D bold bright-black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D bright-black"
deleted = ' +$count '
modified  = ' +$count '
untracked  = '+$count '
format = '([$untracked$modified$deleted]($style))'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A fg:#FFFFFF bold"
format = '[ $time ]($style)'
